// angular/src/app/pages/checkout/checkout.component.ts
import { Component } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { NgToastService } from 'ng-angular-popup';

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './checkout.component.html',
  styleUrl: './checkout.component.css',
})
export class CheckoutComponent {
  constructor(
    private fb: FormBuilder,
    private router: Router,
    private toaster: NgToastService
  ) {}

  checkoutForm = this.fb.group({
    fname: ['', Validators.required],
    lname: ['', Validators.required],
    email: ['', [Validators.required]],
    phone: ['', Validators.required],
    address: ['', Validators.required],
    city: ['', Validators.required],
    state: ['', Validators.required],
    zip: ['', Validators.required],
    payment: ['', Validators.required],
  });

  makePayment() {
    if (this.checkoutForm.valid) {
      // this.alertService.error('Please enter all fields');
      this.toaster.error({
        detail: 'ERROR',
        summary: 'Please enter all fields',
        duration: 3000,
      });
      return;
    }
    this.router.navigate(['/payment']);
  }

  cancelPayment() {
    this.router.navigate(['/']);
  }
}

<div class="font-sans-serif bg-white">
  <div
    class="flex justify-center my-9 max-sm:flex-col gap-12 max-lg:gap-4 h-full"
  >
    <div class="max-w-4xl w-full h-max rounded-md px-4 py-8 sticky top-0">
      <h2 class="text-2xl font-bold text-gray-800">Complete your order</h2>
      <form [formGroup]="checkoutForm" (ngSubmit)="makePayment()">
        <div>
          <h3 class="text-base text-gray-800 mb-4">Personal Details</h3>
          <div class="grid md:grid-cols-2 gap-4">
            <div>
              <input
                type="text"
                placeholder="First Name"
                formControlName="fname"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="Last Name"
                formControlName="lname"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
            <div>
              <input
                type="email"
                placeholder="Email"
                formControlName="email"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
            <div>
              <input
                type="number"
                placeholder="Phone No."
                formControlName="phone"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
          </div>
        </div>

        <div class="mt-8">
          <h3 class="text-base text-gray-800 mb-4">Shipping Address</h3>
          <div class="grid md:grid-cols-2 gap-4">
            <div>
              <input
                type="text"
                placeholder="Address Line"
                formControlName="address"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="City"
                formControlName="city"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="State"
                formControlName="state"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="Zip Code"
                formControlName="zip"
                class="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
              />
            </div>
          </div>
        </div>
        <div class="mt-8">
          <h3 class="text-base text-gray-800 mb-4">Select Payment Method</h3>
          <div class="grid md:grid-cols-2 gap-4">
            <div class="relative">
              <select
                class="block appearance-none w-full bg-gray-100 border border-gray-300 text-gray-800 py-3 px-4 pr-8 rounded-md focus:bg-transparent focus:border-gray-500 focus:outline-none"
                aria-label="Select Version"
                aria-placeholder="Select"
              >
                <option selected>Select Payment Method</option>
                <option value="cheque">Cheque</option>
                <option value="cod">Cash On Delivery</option>
              </select>
              <div
                class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-800"
              >
                <svg
                  class="h-4 w-4"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M10.293 14.293a1 1 0 0 1-1.414 0l-6-6a1 1 0 0 1 1.414-1.414L10 11.586l5.293-5.293a1 1 0 0 1 1.414 1.414l-6 6z"
                    clip-rule="evenodd"
                  />
                </svg>
              </div>
            </div>
          </div>
        </div>

        <div class="flex gap-4 max-md:flex-col mt-8">
          <button
            type="button"
            class="rounded-md px-6 py-3 w-full text-sm tracking-wide bg-transparent hover:bg-gray-100 border border-gray-300 text-gray-800 max-md:order-1"
            (click)="cancelPayment()"
          >
            Cancel
          </button>
          <button
            type="submit"
            class="rounded-md px-6 py-3 w-full text-sm tracking-wide bg-blue-600 hover:bg-blue-700 text-white"
          >
            Complete Purchase
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// react/src/pages/CheckOut.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAlert } from "../components/AlertProvider";

const CheckOut = () => {
  const navigate = useNavigate();
  const showAlert = useAlert();

  const [checkOutData, setCheckOutData] = useState({
    fname: "",
    lname: "",
    email: "",
    phone: "",
    address: "",
    city: "",
    state: "",
    zip: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setCheckOutData({ ...checkOutData, [name]: value });
  };

  const makePayment = () => {
    if (
      !checkOutData.fname ||
      !checkOutData.lname ||
      !checkOutData.email ||
      !checkOutData.phone ||
      !checkOutData.address ||
      !checkOutData.city ||
      !checkOutData.state ||
      !checkOutData.zip
    ) {
      showAlert("Please enter all the Fields ", "error");
      navigate("/payment");
    } else {
    }
  };
  const cancelPayment = () => {
    navigate("/");
  };
  return (
    <div className="font-[sans-serif] bg-white">
      <div className="flex justify-center my-9 max-sm:flex-col gap-12 max-lg:gap-4 h-full">
        <div className="max-w-4xl w-full h-max rounded-md px-4 py-8 sticky top-0">
          <h2 className="text-2xl font-bold text-gray-800">
            Complete your order
          </h2>
          <form className="mt-8">
            <div>
              <h3 className="text-base text-gray-800 mb-4">Personal Details</h3>
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <input
                    type="text"
                    placeholder="First Name"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    id="fname"
                    name="fname"
                    value={checkOutData.fname}
                    onChange={handleChange}
                  />
                </div>

                <div>
                  <input
                    type="text"
                    placeholder="Last Name"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="lname"
                    value={checkOutData.lname}
                    onChange={handleChange}
                  />
                </div>

                <div>
                  <input
                    type="email"
                    placeholder="Email"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="email"
                    value={checkOutData.email}
                    onChange={handleChange}
                  />
                </div>

                <div>
                  <input
                    type="number"
                    placeholder="Phone No."
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="phone"
                    value={checkOutData.phone}
                    onChange={handleChange}
                  />
                </div>
              </div>
            </div>

            <div className="mt-8">
              <h3 className="text-base text-gray-800 mb-4">Shipping Address</h3>
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <input
                    type="text"
                    placeholder="Address Line"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="address"
                    value={checkOutData.address}
                    onChange={handleChange}
                  />
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="City"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="city"
                    value={checkOutData.city}
                    onChange={handleChange}
                  />
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="State"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="state"
                    value={checkOutData.state}
                    onChange={handleChange}
                  />
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="Zip Code"
                    className="px-4 py-3 bg-gray-100 focus:bg-transparent text-gray-800 w-full text-sm rounded-md focus:outline-blue-600"
                    name="zip"
                    value={checkOutData.zip}
                    onChange={handleChange}
                  />
                </div>
              </div>

              <div className="flex gap-4 max-md:flex-col mt-8">
                <button
                  type="button"
                  className="rounded-md px-6 py-3 w-full text-sm tracking-wide bg-transparent hover:bg-gray-100 border border-gray-300 text-gray-800 max-md:order-1"
                  onClick={cancelPayment}
                >
                  Cancel
                </button>
                <button
                  type="button"
                  className="rounded-md px-6 py-3 w-full text-sm tracking-wide bg-blue-600 hover:bg-blue-700 text-white"
                  onClick={makePayment}
                >
                  Complete Purchase
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default CheckOut;
