// angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { UserService } from '../../services/user.service';
import { NgToastService } from 'ng-angular-popup';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  constructor(
    private userService: UserService,
    private router: Router,
    private toaster: NgToastService
  ) {}
  // variable to store the users login status
  isLoggedIn: boolean = false;

  ngOnInit(): void {
    //setting the value as user login staus
    this.isLoggedIn = this.userService.isThereCookie();
    this.userService.userLoggedIn.subscribe((result) => {
      this.isLoggedIn = result;
    });
  }

  /**
   * @purpose to logout user through service
   * @params none
   * @return void
   */
  logOutUser() {
    this.userService.logoutUser().subscribe({
      next: () => {
        this.isLoggedIn = false;
        this.router.navigate(['/login']);
        // emitting the user login status as false
        this.userService.userLoggedIn.emit(false);

        //toaster to give success message to user
        this.toaster.success({
          detail: 'SUCCESS',
          summary: 'User logged out successfully',
          duration: 3000,
        });
      },
      error: (err) => {
        // toaster to give error message to user if any error occurs
        this.toaster.error({
          detail: 'ERROR',
          summary: 'Failed to log out',
          duration: 3000,
        });
      },
    });
  }
}

<header
  class="flex flex-wrap sm:justify-start sm:flex-nowrap w-full bg-white text-sm py-4 dark:bg-neutral-800"
>
  <nav
    class="max-w-[85rem] w-full mx-auto px-4 flex flex-wrap basis-full items-center justify-between"
    aria-label="Global"
  >
    <a
      class="sm:order-1 flex-none text-xl font-semibold dark:text-white"
      routerLink="/"
    >
      <img src="../../../assets/logo.svg" class="text-white" />
    </a>
    <div class="sm:order-3 flex items-center gap-x-2">
      <button
        type="button"
        class="sm:hidden hs-collapse-toggle p-2.5 inline-flex justify-center items-center gap-x-2 rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-transparent dark:border-neutral-700 dark:text-white dark:hover:bg-white/10"
        data-hs-collapse="#navbar-alignment"
        aria-controls="navbar-alignment"
        aria-label="Toggle navigation"
      >
        <svg
          class="hs-collapse-open:hidden flex-shrink-0 size-4"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <line x1="3" x2="21" y1="6" y2="6" />
          <line x1="3" x2="21" y1="12" y2="12" />
          <line x1="3" x2="21" y1="18" y2="18" />
        </svg>
        <svg
          class="hs-collapse-open:block hidden flex-shrink-0 size-4"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M18 6 6 18" />
          <path d="m6 6 12 12" />
        </svg>
      </button>
      @if(isLoggedIn){
      <button
        type="button"
        class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800"
        (click)="logOutUser()"
      >
        logout
      </button>
      }@else {
      <button
        type="button"
        class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800"
      >
        <a routerLink="/login"> login </a>
      </button>
      }
    </div>
    <div
      id="navbar-alignment"
      class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:grow-0 sm:basis-auto sm:block sm:order-2"
    >
      <div
        class="flex flex-col gap-5 mt-5 sm:flex-row sm:items-center sm:mt-0 sm:ps-5"
      >
        <a
          class="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
          routerLink="/"
        >
          Home
        </a>
        <a
          class="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
          routerLink="/products"
        >
          Products
        </a>
        <a
          class="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
          routerLink="/contact"
        >
          Contact
        </a>
        <a
          class="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
          routerLink="/cart"
        >
          Cart
        </a>
      </div>
    </div>
  </nav>
</header>

// react/src/components/Header.jsx
import * as React from "react";
import { Link } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import AccountCircleIcon from "@mui/icons-material/AccountCircle";
import ExitToAppIcon from "@mui/icons-material/ExitToApp";
import { logoutUser } from "../redux/reducers/userReducer";
import { clearCart } from "../redux/reducers/cartReducers";
import { useAlert } from "./AlertProvider";

function Header() {
  const { user } = useSelector((state) => state.userData);

  const dispatch = useDispatch();
  const showAlert = useAlert();

  const handleLogout = () => {
    dispatch(logoutUser());
    dispatch(clearCart());
    showAlert("Use Logged Out Successfully ", "success");
  };

  return (
    <header className="flex flex-wrap sm:justify-start sm:flex-nowrap w-full bg-white text-sm py-4 dark:bg-neutral-800">
      <nav
        className="max-w-[85rem] w-full mx-auto px-4 flex flex-wrap basis-full items-center justify-between"
        aria-label="Global"
      >
        <Link
          className="sm:order-1 flex-none text-xl font-semibold dark:text-white"
          to={"/"}
        >
          <img src="/logo.svg" className="text-white" />
        </Link>
        <div className="sm:order-3 flex items-center gap-x-2">
          <button
            type="button"
            className="sm:hidden hs-collapse-toggle p-2.5 inline-flex justify-center items-center gap-x-2 rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-transparent dark:border-neutral-700 dark:text-white dark:hover:bg-white/10"
            data-hs-collapse="#navbar-alignment"
            aria-controls="navbar-alignment"
            aria-label="Toggle navigation"
          >
            <svg
              className="hs-collapse-open:hidden flex-shrink-0 size-4"
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="3" x2="21" y1="6" y2="6" />
              <line x1="3" x2="21" y1="12" y2="12" />
              <line x1="3" x2="21" y1="18" y2="18" />
            </svg>
            <svg
              className="hs-collapse-open:block hidden flex-shrink-0 size-4"
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M18 6 6 18" />
              <path d="m6 6 12 12" />
            </svg>
          </button>
          {user !== null ? (
            <button
              type="button"
              className="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800"
              onClick={handleLogout}
            >
              <ExitToAppIcon />
            </button>
          ) : (
            <button
              type="button"
              className="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800"
            >
              <Link to={"/login"}>
                <AccountCircleIcon />
              </Link>
            </button>
          )}
        </div>
        <div
          id="navbar-alignment"
          className="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:grow-0 sm:basis-auto sm:block sm:order-2"
        >
          <div className="flex flex-col gap-5 mt-5 sm:flex-row sm:items-center sm:mt-0 sm:ps-5">
            <Link
              className="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
              to={"/"}
            >
              Home
            </Link>
            <Link
              className="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
              to={"/products"}
            >
              Products
            </Link>
            <Link
              className="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
              to={"/contact"}
            >
              Contact
            </Link>
            <Link
              className="font-medium text-gray-600 hover:text-gray-400 dark:text-neutral-400 dark:hover:text-neutral-500"
              to={"/cart"}
            >
              Cart
            </Link>
          </div>
        </div>
      </nav>
    </header>
  );
}
export default Header;
